import logging
import asyncio
import os
from typing import Optional
from app.config import settings

logger = logging.getLogger(__name__)

def _send_smtp_email_sync(
    error_id: str,
    reason: str,
    what_caused: str,
    query: str,
    user_ip: str,
    user_email: Optional[str]
) -> bool:
    import smtplib
    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart

    host = settings.smtp_host
    port = settings.smtp_port
    user = settings.smtp_user
    password = settings.smtp_password
    from_email = settings.smtp_from_email or "noreply@snugpt.rishabhj.in"
    from_name = settings.smtp_from_name or "SNUGPT Security"

    if not host or not user or not password:
        logger.info("[Email] SMTP settings not fully configured. Skipping SMTP dispatch.")
        return False

    recipient = "rj910@snu.edu.in"
    subject = f"🚨 SNUGPT Error Alert [ID: {error_id}]"

    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #d9534f; border-bottom: 2px solid #d9534f; padding-bottom: 8px;">SNUGPT Internal System Error Report</h2>
        <p><strong>Error ID:</strong> <span style="font-family: monospace; background: #f4f4f4; padding: 2px 6px; border-radius: 4px; font-size: 1.1em;">{error_id}</span></p>
        <p><strong>Reason:</strong> <span style="color: #d9534f; font-weight: bold;">{reason}</span></p>
        <p><strong>User Question:</strong> {query}</p>
        <p><strong>IP Address:</strong> {user_ip}</p>
        <p><strong>User Details (Logged in):</strong> {user_email or 'Anonymous'}</p>
        
        <h3>Traceback / Cause:</h3>
        <pre style="background: #222; color: #fff; padding: 15px; border-radius: 6px; overflow-x: auto; font-family: 'Courier New', Courier, monospace; font-size: 12px;">{what_caused}</pre>
        
        <hr style="border: 0; border-top: 1px solid #ccc; margin: 20px 0;" />
        <p style="font-size: 11px; color: #777;">This is an automated system diagnostic alert generated by SNUGPT Neural Engine.</p>
      </body>
    </html>
    """

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{from_name} <{from_email}>"
        msg["To"] = recipient

        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(host, port, timeout=10) as server:
            server.starttls()
            server.login(user, password)
            server.sendmail(from_email, recipient, msg.as_string())
        logger.info("[Email] SMTP email sent successfully for Error ID %s", error_id)
        return True
    except Exception as smtp_err:
        logger.error("[Email] Failed to send email via SMTP: %s", smtp_err)
        return False


def _send_webhook_sync(
    error_id: str,
    reason: str,
    what_caused: str,
    query: str,
    user_ip: str,
    user_email: Optional[str]
) -> bool:
    import requests
    url = settings.contact_apps_script_url
    if not url:
        logger.info("[Email] Webhook URL not configured. Skipping webhook fallback.")
        return False

    payload = {
        "name": "SNUGPT Diagnostics",
        "email": "diagnostics@snugpt.rishabhj.in",
        "subject": f"🚨 SNUGPT System Error Report [ID: {error_id}]",
        "message": f"""
[SNUGPT Internal System Error Report]
--------------------------------------------------
Error ID: {error_id}
Reason: {reason}
User Question: {query}
IP Address: {user_ip}
Logged In User: {user_email or 'Anonymous'}

Traceback / Cause:
--------------------------------------------------
{what_caused}
"""
    }

    try:
        response = requests.post(url, json=payload, timeout=12)
        logger.info("[Email] Webhook trigger response: %s", response.status_code)
        return response.status_code == 200
    except Exception as webhook_err:
        logger.error("[Email] Failed to trigger Apps Script webhook: %s", webhook_err)
        return False


async def send_error_email(
    error_id: str,
    reason: str,
    what_caused: str,
    query: str,
    user_ip: str,
    user_email: Optional[str] = None
):
    """Asynchronously send an error telemetry alert via SMTP and fall back to Google Apps Script webhook."""
    def run_dispatches():
        _send_smtp_email_sync(error_id, reason, what_caused, query, user_ip, user_email)
        _send_webhook_sync(error_id, reason, what_caused, query, user_ip, user_email)

    await asyncio.to_thread(run_dispatches)
